### ISSUE TITLE
Unhandled 'error' event

### ISSUE THREAD

**Issue by boothead** [netlify-templates/victor-hugo#158]
**- Do you want to request a *feature* or report a *bug*?**

A Bug

**- What is the current behavior?**

Instructions from README don't work.

**- If the current behavior is a bug, please provide the steps to reproduce.**

I've run `npm install` and then:

```
⇒  npm run preview                                                                                                                                                                                ~/dev/victor-hugo

> victor-hugo@1.0.0 preview /home/ben/dev/victor-hugo
> run-p preview:**


> victor-hugo@1.0.0 preview:hugo /home/ben/dev/victor-hugo
> npm run start:hugo -- -D -F


> victor-hugo@1.0.0 preview:webpack /home/ben/dev/victor-hugo
> npm run start:webpack


> victor-hugo@1.0.0 start:webpack /home/ben/dev/victor-hugo
> webpack-dev-server --config webpack.dev.js


> victor-hugo@1.0.0 start:hugo /home/ben/dev/victor-hugo
> hugo -d ../dist -s site -vw "-D" "-F"

WARN 2019/01/23 12:38:26 No translation bundle found for default language "en"
WARN 2019/01/23 12:38:26 Translation func for language en not found, use default.
WARN 2019/01/23 12:38:26 i18n not initialized, check that you have language file (in i18n) that matches the site language or the default language.
INFO 2019/01/23 12:38:26 Using config file: /home/ben/dev/victor-hugo/site/config.toml
Building sites … INFO 2019/01/23 12:38:26 syncing static files to /home/ben/dev/victor-hugo/dist/
INFO 2019/01/23 12:38:26 found taxonomies: map[string]string{"tag":"tags", "category":"categories"}

                   | EN  
+------------------+----+
  Pages            |  3  
  Paginator pages  |  0  
  Non-page files   |  0  
  Static files     |  1  
  Processed images |  0  
  Aliases          |  0  
  Sitemaps         |  1  
  Cleaned          |  0  

Watching for changes in /home/ben/dev/victor-hugo/site/content
Press Ctrl+C to stop
Watching for config changes in /home/ben/dev/victor-hugo/site/config.toml
clean-webpack-plugin: /home/ben/dev/victor-hugo/dist/**/*.js has been removed.
clean-webpack-plugin: /home/ben/dev/victor-hugo/dist/**/*.css has been removed.
clean-webpack-plugin: /home/ben/dev/victor-hugo/site/content/webpack.json has been removed.
events.js:167
      throw er; // Unhandled 'error' event
      ^

Error: listen EADDRINUSE 127.0.0.1:3000
    at Server.setupListenHandle [as _listen2] (net.js:1286:14)
    at listenInCluster (net.js:1334:12)
    at GetAddrInfoReqWrap.doListen [as callback] (net.js:1460:7)
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:62:10)
Emitted 'error' event at:
    at emitErrorNT (net.js:1313:8)
    at process._tickCallback (internal/process/next_tick.js:63:19)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! victor-hugo@1.0.0 start:webpack: `webpack-dev-server --config webpack.dev.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the victor-hugo@1.0.0 start:webpack script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/ben/.npm/_logs/2019-01-23T12_38_27_550Z-debug.log
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! victor-hugo@1.0.0 preview:webpack: `npm run start:webpack`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the victor-hugo@1.0.0 preview:webpack script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/ben/.npm/_logs/2019-01-23T12_38_27_563Z-debug.log
Total in 740 ms
ERROR: "preview:webpack" exited with 1.
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! victor-hugo@1.0.0 preview: `run-p preview:**`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the victor-hugo@1.0.0 preview script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/ben/.npm/_logs/2019-01-23T12_38_27_591Z-debug.log
```

**- What is the expected behavior?**

I'd expect a running service on localhost :-)

**- Please mention your node.js, NPM, Hugo and operating system version.**

```
⇒  npm -v
6.4.1
⇒  node -v                                                                                           
v10.12.0
⇒  hugo version
Hugo Static Site Generator v0.50/extended linux/amd64 BuildDate: unknown
⇒  uname -a
Linux office 4.14.87 #1-NixOS SMP Sat Dec 8 12:03:41 UTC 2018 x86_64 GNU/Linux
```

**Comment by erquhart** [comment]
I'm unable to reproduce. The error you're seeing indicates that port 3000 is unavailable on your machine, I'd start there.
