### ISSUE TITLE
TypeError: CleanWebpackPlugin is not a constructor

### ISSUE THREAD

**Issue by jSwtch** [netlify-templates/victor-hugo#187]
---------------------------------------------------
BUG REPORT INFORMATION
---------------------------------------------------
Use the commands below to provide key information from your environment:
You do NOT have to include this information if this is a FEATURE REQUEST
-->

**- Do you want to request a *feature* or report a *bug*?**
Bug

**- What is the current behavior?**
error on npm start

**- If the current behavior is a bug, please provide the steps to reproduce.**
error on npm start

```
    new CleanWebpackPlugin({
    ^

TypeError: CleanWebpackPlugin is not a constructor
    at Object.<anonymous> (J:\DEVELOP\2019-victor-hugo\victor-hugo-master\webpack.dev.js:28:5)
    at Module._compile (internal/modules/cjs/loader.js:776:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:787:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
    at Module.require (internal/modules/cjs/loader.js:690:17)
    at require (internal/modules/cjs/helpers.js:25:18)
```

**- What is the expected behavior?**
start fine - I see that 

`const CleanWebpackPlugin = require('clean-webpack-plugin');`

is the correct syntax (https://github.com/johnagan/clean-webpack-plugin/issues/143)

So not sure where the error is from 

**- Please mention your node.js, NPM, Hugo and operating system version.**
λ node -v
v10.16.0

λ npm -version
6.9.0

λ hugo version
Hugo Static Site Generator v0.55.6/extended windows/amd64 BuildDate: unknown

Win 10 OS 64bit

**Comment by erquhart** [comment]
Fixed in #185.
