### ISSUE TITLE
npm start throws error after fresh repo install

### ISSUE THREAD

**Issue by SebastianSchirmer** [netlify-templates/victor-hugo#498]
**- Do you want to request a *feature* or report a *bug*?**
I am sorry to bother you guys here but I am unable to find any valuable information anywhere else right now.
I am asking for help or a hint as I don't think there is a bug but that there is some kind of misconfiguration on my end.

**- What is the current behavior?**
npm start throws an error after a fresh install of the repo.

However, when running hugo -d ../dist -s site -vw separately, this commands runs without error. Also running yarn webpack-dev-server --config webpack.dev.js --hot runs without error.

**- If the current behavior is a bug, please provide the steps to reproduce.**
Run npm start

**- What is the expected behavior?**
npm start does not throw an error.

**- Please mention your node.js, NPM, Hugo and operating system version.**
node v12.16.2
npm v6.14.4
Hugo v0.78.2

I am pasting the log file produced:

0 info it worked if it ends with ok
1 verbose cli [ '/usr/local/bin/node', '/usr/local/bin/npm', 'start' ]
2 info using npm@6.14.4
3 info using node@v12.16.2
4 verbose run-script [ 'prestart', 'start', 'poststart' ]
5 info lifecycle victor-hugo@1.0.0~prestart: victor-hugo@1.0.0
6 info lifecycle victor-hugo@1.0.0~start: victor-hugo@1.0.0
7 verbose lifecycle victor-hugo@1.0.0~start: unsafe-perm in lifecycle true
8 verbose lifecycle victor-hugo@1.0.0~start: PATH: /usr/local/lib/node_modules/npm/node_modules/npm-lifecycle/node-gyp-bin:/Users/schirmeur/sites/quiply-website-hugo-cms/node_modules/.bin:/usr/local/bin:/Users/schirmeur/.node/bin:/Library/Java/JavaVirtualMachines/jdk1.8.0_45.jdk/Contents/Home/bin:/Users/schirmeur/Library/Android/sdk/platform-tools:/usr/local/opt/ruby/bin:/Users/schirmeur/.node/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/git/bin:/Users/schirmeur/Library/Android/sdk/tools:/Users/schirmeur/Library/Android/sdk/platforms:/Users/schirmeur/.rvm/bin
9 verbose lifecycle victor-hugo@1.0.0~start: CWD: /Users/schirmeur/sites/quiply-website-hugo-cms
10 silly lifecycle victor-hugo@1.0.0~start: Args: [ '-c', 'run-p start:**' ]
11 silly lifecycle victor-hugo@1.0.0~start: Returned: code: 1  signal: null
12 info lifecycle victor-hugo@1.0.0~start: Failed to exec start script
13 verbose stack Error: victor-hugo@1.0.0 start: `run-p start:**`
13 verbose stack Exit status 1
13 verbose stack     at EventEmitter.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/npm-lifecycle/index.js:332:16)
13 verbose stack     at EventEmitter.emit (events.js:310:20)
13 verbose stack     at ChildProcess.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/npm-lifecycle/lib/spawn.js:55:14)
13 verbose stack     at ChildProcess.emit (events.js:310:20)
13 verbose stack     at maybeClose (internal/child_process.js:1021:16)
13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:286:5)
14 verbose pkgid victor-hugo@1.0.0
15 verbose cwd /Users/schirmeur/sites/quiply-website-hugo-cms
16 verbose Darwin 18.7.0
17 verbose argv "/usr/local/bin/node" "/usr/local/bin/npm" "start"
18 verbose node v12.16.2
19 verbose npm  v6.14.4
20 error code ELIFECYCLE
21 error errno 1
22 error victor-hugo@1.0.0 start: `run-p start:**`
22 error Exit status 1
23 error Failed at the victor-hugo@1.0.0 start script.
23 error This is probably not a problem with npm. There is likely additional logging output above.
24 verbose exit [ 1, true ]

**Comment by SebastianSchirmer** [comment]
I had to update the npm package hugo-bin to version 0.67.1 and the error was gone. I am running hugo version 0.78.2 so there might have been an incompatibility.
