### ISSUE TITLE
Apple Silicon issues with hugo-bin and node-sass (and workaround)

### ISSUE THREAD

**Issue by sergioisidoro** [netlify-templates/victor-hugo#521]
Currently this project does not work with Apple Silicon (M1) processors. 

Currently this issue: https://github.com/sass/node-sass/issues/3033 prevents node-sass from being installed, and hugo-bin seems go give:

```
Error: spawn /Users/sergio/Developer/victor-hugo/node_modules/hugo-bin/vendor EACCES
    at Process.ChildProcess._handle.onexit (node:internal/child_process:282:19)
    at onErrorNT (node:internal/child_process:480:16)
    at processTicksAndRejections (node:internal/process/task_queues:83:21)
Emitted 'error' event on ChildProcess instance at:
    at Process.ChildProcess._handle.onexit (node:internal/child_process:288:12)
    at onErrorNT (node:internal/child_process:480:16)
    at processTicksAndRejections (node:internal/process/task_queues:83:21) {
  errno: -13,
```

For anyone searching for solutions, this is what worked for me:

1. Replace `node-sass` dependency by `"sass": "^1.35.1",`
2. Remove `hugo-bin` from the dependencies
2.1. Remove node modules
2.2. `npm install`
3. 🪄 Magic

(To work, this assumes you have hugo installed globally. [Binaries for Apple Silicon](https://gohugo.io/getting-started/installing/) are already available)

Another possibility (that I have not tested) is to use rosetta:
```
rm -rf node_modules
npm install --target_arch=x64
``` 

Leaving this here in hopes it will help someone.
Happy coding 🎉

**Comment by ebauger** [comment]
hugo-bin seam to work well if you bum to v6.0.0

For my side, I have more issue with **mini-css-extract-plugin** **css-loader** and **sass-loader**

When I run ```yarn build```

here the output

```
ERROR in ./src/scss/main.scss (./node_modules/mini-css-extract-plugin/dist/loader.js!./node_modules/css-loader/dist/cjs.js!./node_modules/sass-loader/dist/cjs.js!./src/scss/main.scss)
Module build failed (from ./node_modules/mini-css-extract-plugin/dist/loader.js):
ModuleBuildError: Module build failed (from ./node_modules/sass-loader/dist/cjs.js):
TypeError: this.getOptions is not a function
    at Object.loader (/website-hugo/node_modules/sass-loader/dist/index.js:25:24)
    at /website-hugo/node_modules/webpack/lib/NormalModule.js:316:20
    at /website-hugo/node_modules/loader-runner/lib/LoaderRunner.js:367:11
    at /website-hugo/node_modules/loader-runner/lib/LoaderRunner.js:233:18
 @ ./src/scss/main.scss 2:26-193 43:4-64:5 46:18-185
 @ multi ./src/main.js ./src/scss/main.scss
Child mini-css-extract-plugin node_modules/css-loader/dist/cjs.js!node_modules/sass-loader/dist/cjs.js!src/scss/main.scss:
     1 asset
    Entrypoint mini-css-extract-plugin = *
    [0] ./node_modules/css-loader/dist/cjs.js!./node_modules/sass-loader/dist/cjs.js!./src/scss/main.scss 268 bytes {0} [built] [failed] [1 error]

    ERROR in ./src/scss/main.scss (./node_modules/css-loader/dist/cjs.js!./node_modules/sass-loader/dist/cjs.js!./src/scss/main.scss)
    Module build failed (from ./node_modules/sass-loader/dist/cjs.js):
    TypeError: this.getOptions is not a function
        at Object.loader (/website-hugo/node_modules/sass-loader/dist/index.js:25:24)
```

**Comment by sergioisidoro** [comment]
Nice catch with the `hugo-bin`. Makes sense :)

Did you check if hugo it was running on Rosetta compatibility mode or on native apple silicon?
Should we make a pull request bumping hugo-bin then?

I've only used `npm install / npm start` and everything worked fine. 
Did not check how things went with yarn.

**Comment by ebauger** [comment]
@sergioisidoro

I have an apple silicon (mac mini m1) and I'll try to make a workaround on my local machine first.

For the contribution on this repo (pull request), I don't know right now how to proceed.

I'll continuing my investigation tomorrow and I post UPDATES if needed.

**Comment by ebauger** [comment]
@sergioisidoro 

I made a PR #522 for bumping all the old deprecated packages (not all, but the minimum package) for running without errors.

It should work on `start` and on `build`

**Comment by timtorres** [comment]
I have an Intel processor (Big Sur v11.4) but was also having issues with `node-sass`. I'm pretty new to CLI and this all so I spent a lot of time trying to diagnose and fix the errors. Your steps 1-3 worked perfectly for me! I also installed `hugo-bin` manually afterward as I don't think I had it installed globally.

**Comment by ebauger** [comment]
@timtorres You are right. You can check my fork [here](https://github.com/ebauger/victor-hugo).

**Comment by timtorres** [comment]
@ebauger I already have a project started but was looking through your fork to compare. I saw that the Optimize CSS Assets Webpack Plugin says:
> ⚠️ For webpack v5 or above please use css-minimizer-webpack-plugin instead.
but you are still using it. Would this cause any problems? Hope I'm not hijacking this issue - issues aren't enabled on the fork.
